// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function GreetMany(arg1:string,arg2:string):Promise<number>;

export function SeedMany(arg1:string,arg2:string):Promise<void>;
